### ISSUE TITLE
2.1的支持吗

### ISSUE THREAD

**Issue by MrLiu0635** [xakepbean/core-setup-debug#1]
您好，一直采用您的方式过的目录整理这一关，请问能不能帮整理一个2.1的dll，谢谢

**Comment by xakepbean** [comment]
@MrLiu0635 已经更新到2.1.3版本了

**Comment by MrLiu0635** [comment]
谢谢 @xakepbean

**Comment by MrLiu0635** [comment]
@xakepbean 

您好，求助！

最近在扩展跨平台，发现工具这linux环境上这种目录就失效了，是不是这个文件也需要针对不同平台生成？我能找到代码，也知道怎么修改，可是不知道怎么编译出其他平台(centos\ubuntu..)的版本

**Comment by xakepbean** [comment]
selfRuntime.zip
我刚才上传了这个文件，你把这个下载下来。
这是一个控制台程序的源码，你编译一下。
然后你正常的指定操作系统的发布方式去发布你的程序，然后执行 控制台程序，并把刚才把刚才发布程序的路径作为参数，控制台程序会自动把文件转移到runtime的文件夹里去。

原理是利用配置.runtimeconfig.json文件里一个参数 additionalProbingPaths就可以了
{ "runtimeOptions": {"additionalProbingPaths": [".\\runtime\\" ]}}

本来抽空把控制台程序弄一个dotnet的一个插件的，但一直抽不出空了。源码给你，你自己凑合用吧

**Comment by xakepbean** [comment]
@MrLiu0635 按上面的方法处理吧

**Comment by MrLiu0635** [comment]
谢谢你！
Java转DotNet来的，很多东西都不懂，我研究一下。

谢谢

**Comment by liesauer** [comment]
可以了解下 [`NetCoreBeauty`](https://github.com/nulastudio/NetCoreBeauty) 这个项目，完全傻瓜式，编译时支持`windows`、`linux`、`osx`三平台自动处理
